package qwatch.jenkins.actor;

import io.vavr.collection.List;
import io.vavr.control.Either;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import qwatch.jenkins.model.maven.RawLog;
import qwatch.jenkins.model.maven.RawLog.Level;

/**
 * Jenkins log reader reads console log generated by Jenkins.
 *
 * @author Mincong Huang
 * @since 1.0
 */
public class JenkinsLogReader {

  private static final Logger logger = LoggerFactory.getLogger(JenkinsLogReader.class);

  private static final String MVN_START_PREFIX = "Executing Maven:";
  private static final String MVN_END_PREFIX = "[INFO] Final Memory:";

  Either<String, List<RawLog>> read(Path logFile) {
    java.util.List<String> lines;
    try {
      lines = Files.readAllLines(logFile);
    } catch (IOException e) {
      return Either.left("Failed to read log file: " + logFile.toAbsolutePath());
    }

    // Before Maven logs: skip
    var it = lines.iterator();
    var isMaven = false;
    var beforeLines = 0;
    while (it.hasNext() && !isMaven) {
      var line = it.next();
      if (line.startsWith(MVN_START_PREFIX)) {
        isMaven = true;
      }
      beforeLines++;
    }

    // During Maven logs: process
    var logs = new java.util.LinkedList<RawLog>();
    while (it.hasNext() && isMaven) {
      var line = it.next();
      if (hasLevel(line)) {
        if (line.startsWith(MVN_END_PREFIX)) {
          isMaven = false;
          logs.add(RawLog.parseTrusted(line));
          if (it.hasNext()) {
            logs.add(RawLog.parseTrusted(it.next()));
          }
        } else {
          logs.add(RawLog.parseTrusted(line));
        }
      } else  {
        var last = logs.peekLast();
        logs.add(last.extendMsg(line));
      }
    }

    var afterLines = 0;
    while (it.hasNext()) {
      it.next();
      afterLines++;
    }
    System.out.printf(
        "Before: %,d lines, Maven: %,d logs, After: %,d lines.",
        beforeLines, logs.size(), afterLines);
    return Either.left("Not implemented yet.");
  }

  private static boolean hasLevel(String line) {
    for (var level : Level.values()) {
      if (line.startsWith(level.marker())) {
        return true;
      }
    }
    return false;
  }

  public static void main(String[] args) {
    JenkinsLogReader reader = new JenkinsLogReader();
    reader.read(Paths.get("/Users/mincong/jenkins/jenkins-artifacts/nos-master.270/jenkins.log"));
  }
}
